#pragma once

#define ENCODER_RESOLUTION 4

/* RGB (SK6812 / WS2812) */
#define WS2812_DI_PIN GP12
#define RGBLIGHT_LED_COUNT 6
#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_EFFECT_STATIC_LIGHT
#define RGBLIGHT_SLEEP

/* OLED */
#define OLED_DISPLAY_128X32
#define OLED_TIMEOUT 0